CREATE TABLE IF NOT EXISTS checklist (
  checklist_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id integer NOT NULL,
  fecha_hora timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS checklist_detalle (
  detalle_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  checklist_id integer NOT NULL REFERENCES checklist(checklist_id) ON DELETE CASCADE,
  insumo_id integer NOT NULL REFERENCES insumo(insumo_id) ON DELETE CASCADE,
  stock_teorico numeric NOT NULL,
  stock_contado numeric NOT NULL);