// <auto-generated />
using System;
using CafeAroma.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CafeAroma.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260928035807_AgregarChecklist")]
    partial class AgregarChecklist
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CafeAroma.Api.Models.AlertaStock", b =>
                {
                    b.Property<int>("AlertaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("alerta_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlertaId"));

                    b.Property<bool>("Atendida")
                        .HasColumnType("boolean")
                        .HasColumnName("atendida");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("InsumoId")
                        .HasColumnType("integer")
                        .HasColumnName("insumo_id");

                    b.Property<decimal>("NivelDetectado")
                        .HasColumnType("numeric")
                        .HasColumnName("nivel_detectado");

                    b.HasKey("AlertaId");

                    b.ToTable("alerta_stock");
                });

            modelBuilder.Entity("CafeAroma.Api.Models.Bitacora", b =>
                {
                    b.Property<int>("BitacoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bitacora_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BitacoraId"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accion");

                    b.Property<string>("Detalle")
                        .HasColumnType("text")
                        .HasColumnName("detalle");

                    b.Property<string>("EntidadAfectada")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entidad_afectada");

                    b.Property<int?>("EntidadId")
                        .HasColumnType("integer")
                        .HasColumnName("entidad_id");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("BitacoraId");

                    b.ToTable("bitacora");
                });

            modelBuilder.Entity("CafeAroma.Api.Models.Checklist", b =>
                {
                    b.Property<int>("ChecklistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("checklist_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChecklistId"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("ChecklistId");

                    b.ToTable("checklist");
                });

            modelBuilder.Entity("CafeAroma.Api.Models.ChecklistDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("detalle_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("ChecklistId")
                        .HasColumnType("integer")
                        .HasColumnName("checklist_id");

                    b.Property<int>("InsumoId")
                        .HasColumnType("integer")
                        .HasColumnName("insumo_id");

                    b.Property<decimal>("StockContado")
                        .HasColumnType("numeric")
                        .HasColumnName("stock_contado");

                    b.Property<decimal>("StockTeorico")
                        .HasColumnType("numeric")
                        .HasColumnName("stock_teorico");

                    b.HasKey("DetalleId");

                    b.HasIndex("ChecklistId");

                    b.HasIndex("InsumoId");

                    b.ToTable("checklist_detalle");
                });

            modelBuilder.Entity("CafeAroma.Api.Models.CierreCaja", b =>
                {
                    b.Property<int>("CierreCajaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cierre_caja_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CierreCajaId"));

                    b.Property<decimal>("Diferencia")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric")
                        .HasColumnName("diferencia");

                    b.Property<decimal>("EfectivoContado")
                        .HasColumnType("numeric")
                        .HasColumnName("efectivo_contado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<decimal>("TotalVentas")
                        .HasColumnType("numeric")
                        .HasColumnName("total_ventas");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("CierreCajaId");

                    b.ToTable("cierre_caja");
                });

            modelBuilder.Entity("CafeAroma.Api.Models.HistoricoPrecio", b =>
                {
                    b.Property<int>("HistoricoPrecioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("historico_precio_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoricoPrecioId"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<decimal>("PrecioAnterior")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_anterior");

                    b.Property<decimal>("PrecioNuevo")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_nuevo");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("HistoricoPrecioId");

                    b.ToTable("historico_precio", (string)null);
                });

            modelBuilder.Entity("CafeAroma.Api.Models.Insumo", b =>
                {
                    b.Property<int>("InsumoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("insumo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InsumoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<decimal>("StockActual")
                        .HasColumnType("numeric")
                        .HasColumnName("stock_actual");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("numeric")
                        .HasColumnName("stock_minimo");

                    b.HasKey("InsumoId");

                    b.ToTable("insumo");
                });

            modelBuilder.Entity("CafeAroma.Api.Models.Merma", b =>
                {
                    b.Property<int>("MermaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("merma_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MermaId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("InsumoId")
                        .HasColumnType("integer")
                        .HasColumnName("insumo_id");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("MermaId");

                    b.HasIndex("InsumoId");

                    b.ToTable("merma");
                });

            modelBuilder.Entity("CafeAroma.Api.Models.MovimientoInventario", b =>
                {
                    b.Property<int>("MovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("movimiento_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovimientoId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("InsumoId")
                        .HasColumnType("integer")
                        .HasColumnName("insumo_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("MovimientoId");

                    b.ToTable("movimiento_inventario");
                });

            modelBuilder.Entity("CafeAroma.Api.Models.ProductoInsumo", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<int>("InsumoId")
                        .HasColumnType("integer")
                        .HasColumnName("insumo_id");

                    b.Property<decimal>("CantidadNecesaria")
                        .HasColumnType("numeric")
                        .HasColumnName("cantidad_necesaria");

                    b.HasKey("ProductoId", "InsumoId");

                    b.ToTable("producto_insumo");
                });

            modelBuilder.Entity("CafeAroma.Api.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contrasena_hash");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.HasKey("UsuarioId");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("CafeAroma.Api.Models.ChecklistDetalle", b =>
                {
                    b.HasOne("CafeAroma.Api.Models.Checklist", null)
                        .WithMany("Detalles")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeAroma.Api.Models.Insumo", "Insumo")
                        .WithMany()
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("CafeAroma.Api.Models.Merma", b =>
                {
                    b.HasOne("CafeAroma.Api.Models.Insumo", "Insumo")
                        .WithMany()
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("CafeAroma.Api.Models.Checklist", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
